language: php

php:
    - 5.6

before_script:
    - composer install

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit --configuration phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls